### ISSUE TITLE
Serial port error.

### ISSUE THREAD

**Issue by vstadnytskyi** [vstadnytskyi/syringe-pump#1]
Serial port error. I am not sure how I got this. It could be history-dependent.

```
user:syringe-pump user-13$ ipython3
r^[[APython 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: run syringe_pump/device_io.py
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user-13/All-Projects-on-user/LaserLab/Software/syringe-pump/syringe_pump/device.py", line 277, in run
    self.run_once()
  File "/Users/user-13/All-Projects-on-user/LaserLab/Software/syringe-pump/syringe_pump/device.py", line 262, in run_once
    self.position = self.get_position()
  File "/Users/user-13/All-Projects-on-user/LaserLab/Software/syringe-pump/syringe_pump/device.py", line 442, in get_position
    reply = self.driver._get_position()
  File "/Users/user-13/All-Projects-on-user/LaserLab/Software/syringe-pump/syringe_pump/driver.py", line 312, in _get_position
    reply = self.query(command = '/1?18\r')
  File "/Users/user-13/All-Projects-on-user/LaserLab/Software/syringe-pump/syringe_pump/driver.py", line 233, in query
    reply = self.read(port = port)
  File "/Users/user-13/All-Projects-on-user/LaserLab/Software/syringe-pump/syringe_pump/driver.py", line 188, in read
    reply = port.readline()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

**Comment by vstadnytskyi** [comment]
i was creating two instances of the port connection. I couldn't open the port in the second instance.
